// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Upgrade:                              1
// Endpoints:                            6
// Async Callback:                       1
// Total number of exported functions:   9

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    edu_chain
    (
        init => init
        upgrade => upgrade
        issueCertificate => issue_certificate
        registerUser => register_user
        depositRewards => deposit_rewards
        setRewardsTokenIdentifier => set_rewards_token_identifier
        issueToken => issue_token
        setLocalRoles => set_local_roles
    )
}

multiversx_sc_wasm_adapter::async_callback! { edu_chain }
